version: '3.4'

services:
  api1:
    build:
      context: .
      dockerfile: API1/Dockerfile
    ports:
      - "5001:80"
  
  api2:
    build:
      context: .
      dockerfile: API2/Dockerfile
    ports:
      - "5002:80"